### ISSUE TITLE
Cannot find brunch module

### ISSUE THREAD

**Issue by ijt** [chrismccord/phoenix_chat_example#15]
When I run mix phoenix.server on this it reports this error:

[info] Running Chat.Endpoint with Cowboy on port 4000 (http)
module.js:338
    throw err;
          ^
Error: Cannot find module '/Users/issactrotts/elixir/phoenix_chat_example/node_modules/brunch/bin/brunch'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by chrismccord** [comment]
Did you run `npm install` per the instructions in the readme?

**Comment by ijt** [comment]
I did just now, but it's still not working.

$ npm install
\
> node-sass@2.0.1 install /Users/issactrotts/elixir/phoenix_chat_example/node_modules/sass-brunch/node_modules/node-sass
> node scripts/install.js


> node-sass@2.0.1 postinstall /Users/issactrotts/elixir/phoenix_chat_example/node_modules/sass-brunch/node_modules/node-sass
> node scripts/build.js

`darwin-x64-node-0.12` exists; testing
Binary is fine; exiting
npm WARN unmet dependency /Users/issactrotts/elixir/phoenix_chat_example/node_modules/babel-brunch/node_modules/babel-core/node_modules/source-map-support requires source-map@'0.1.32' but will load
npm WARN unmet dependency /Users/issactrotts/elixir/phoenix_chat_example/node_modules/babel-brunch/node_modules/babel-core/node_modules/source-map,
npm WARN unmet dependency which is version 0.4.2
sass-brunch@1.8.10 node_modules/sass-brunch
├── promise@6.1.0 (asap@1.0.0)
├── progeny@0.5.2 (async-each@0.1.6, fs-mode@1.0.1)
└── node-sass@2.0.1 (get-stdin@4.0.1, object-assign@2.0.0, replace-ext@0.0.1, cross-spawn@0.2.6, nan@1.7.0, chalk@0.5.1, semver@4.3.1, mkdirp@0.5.0, shelljs@0.3.0, meow@3.1.0, npmconf@2.1.1, gaze@0.5.1, sass-graph@1.1.0, mocha@2.2.1, request@2.53.0)
$ mix phoenix.server
[info] Running Chat.Endpoint with Cowboy on port 4000 (http)
module.js:338
    throw err;
          ^
Error: Cannot find module '/Users/issactrotts/elixir/phoenix_chat_example/node_modules/brunch/lib/cli'
...

**Comment by ijt** [comment]
The demo works though. Maybe it's no big deal.

**Comment by ijt** [comment]
I got rid of the npm warnings and lack of brunch by doing

    rm -rf node_modules
    npm cache clean
    npm install
