### ISSUE TITLE
direct websocket connection

### ISSUE THREAD

**Issue by aposto** [chrismccord/phoenix_chat_example#23]
I'm using direct url for websocket client.
URL: ws://localhost:4000/socket/websocket?user_id=123 (wscat of node.js)
Why disconnect after connected that url.
I hope directly connect for application not web.
Thanks.

**Comment by chrismccord** [comment]
wscat of node.js does not send a compliant `host` header per the RFC spec. Can you try upgrading your wscat version? It looks like the issue was patched in July;
https://github.com/websockets/ws/pull/504
