### ISSUE TITLE
Contributions to tests welcome?

### ISSUE THREAD

**Issue by PragTob** [chrismccord/phoenix_chat_example#26]
Hi there,

thanks once again for all your work :)

Just pinging to know if you'd be interested in PRs adding tests (unit or maybe even integration)?

Thanks + Cheers,
Tobi

**Comment by nathany** [comment]
A full example of testing channels would be really helpful.

**Comment by chrismccord** [comment]
PR's accepted! :)

**Comment by PragTob** [comment]
Cool then I'll close this up and maybe get to some tests some time :)
