### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by kklepper** [chrismccord/phoenix_chat_example#27]
I started with opening http://phoenixchat.herokuapp.com/ in Firefox only to see nothing. I couldn't even open the source window, as the right mouse button didn't do anything. So I opened the application in chrome and played a little bit, seeing mostly pings, until the display hit the bottom and disappeared. No automatic scrolling, no scrollbar. Too bad for a showcase. (Win 7 64)

**Comment by nathany** [comment]
It looks like [app.js](https://github.com/chrismccord/phoenix_chat_example/blob/master/web/static/js/app.js) is using ES6 arrow functions (`=>`). Maybe those aren't supported in Firefox yet?

**Comment by chrismccord** [comment]
The js is transpiled, so it seems unrelated. PR's accepted for any FF issues. Thanks!

**Comment by nathany** [comment]
That's cool.
