### ISSUE TITLE
Phoenix 1.4 (master) and Jason gives (ArgumentError) argument error Chat.Endpoint.HTTP (cowboy_protocol) terminated on SINGLE CORE CPU

### ISSUE THREAD

**Issue by niccolox** [chrismccord/phoenix_chat_example#50]
I found this bug/error/issue on another project which I am trying to upgrade to Phoenix 1.4 (master actually) and Jason. 

In fact, I had been running in production with Phoenix 1.4 (master) and channels where working, but, then it broke. I know, risk of chasing HEAD <>

I managed to replicate it I think, using a fork of this project and I would be curious on how to update code etc to bypass. 

The fork is https://github.com/devekkoio/phoenix_chat_example

the error is hard to catch as it only happens on DEV or PROD ( I think ) on a remote connection

i.e. it doesnt show up on local dev macbook, or even an Ubuntu workstation, but when pushed to Linode it fails. Havent tried other clouds, but have rebuilt on Linode using Xenial and Bionic, same issue. 

the error on cowboy 1 is below, there is also a cowboy 2 error which I will skip for now

```
[error] Ranch protocol #PID<0.386.0> of listener Chat.Endpoint.HTTP (cowboy_protocol) terminated
** (exit) exited in: Phoenix.Endpoint.CowboyWebSocket.resume()
    ** (EXIT) an exception was raised:
        ** (ArgumentError) argument error
            :erlang.phash2({#PID<0.386.0>, #Reference<0.412873586.60293121.193514>}, 0)
            (phoenix) lib/phoenix/socket/pool_supervisor.ex:11: Phoenix.Socket.PoolSupervisor.start_child/3
            (phoenix) lib/phoenix/channel/server.ex:45: anonymous fn/3 in Phoenix.Channel.Server.join/4
            (chat) lib/chat/endpoint.ex:1: Chat.Endpoint.instrument/4
            (phoenix) lib/phoenix/socket.ex:590: Phoenix.Socket.handle_in/4
            (phoenix) lib/phoenix/endpoint/cowboy_websocket.ex:84: Phoenix.Endpoint.CowboyWebSocket.websocket_handle/3
            (cowboy) /var/www/phx_chat_14/deps/cowboy/src/cowboy_websocket.erl:588: :cowboy_websocket.handler_call/7
            (phoenix) lib/phoenix/endpoint/cowboy_websocket.ex:54: Phoenix.Endpoint.CowboyWebSocket.resume/3
[error] Ranch protocol #PID<0.388.0> of listener Chat.Endpoint.HTTP (cowboy_protocol) terminated
** (exit) exited in: Phoenix.Endpoint.CowboyWebSocket.resume()
    ** (EXIT) an exception was raised:
        ** (ArgumentError) argument error
            :erlang.phash2({#PID<0.388.0>, #Reference<0.412873586.60293121.194098>}, 0)
            (phoenix) lib/phoenix/socket/pool_supervisor.ex:11: Phoenix.Socket.PoolSupervisor.start_child/3
            (phoenix) lib/phoenix/channel/server.ex:45: anonymous fn/3 in Phoenix.Channel.Server.join/4
            (chat) lib/chat/endpoint.ex:1: Chat.Endpoint.instrument/4
            (phoenix) lib/phoenix/socket.ex:590: Phoenix.Socket.handle_in/4
            (phoenix) lib/phoenix/endpoint/cowboy_websocket.ex:84: Phoenix.Endpoint.CowboyWebSocket.websocket_handle/3
            (cowboy) /var/www/phx_chat_14/deps/cowboy/src/cowboy_websocket.erl:588: :cowboy_websocket.handler_call/7
            (phoenix) lib/phoenix/endpoint/cowboy_websocket.ex:54: Phoenix.Endpoint.CowboyWebSocket.resume/3

```

**Comment by chrismccord** [comment]
Thanks for opening this issue. I believe the cause is a bug in our new socket supervisor in cases where you are on a single-core machine (`System.schedulers_online() == 0`). Can you please try the following as a temporary workaround as well as a way to help verify this issue?

In your user_socket.ex:

```elixir
defmodule AppWeb.UserSocket do
  use Phoenix.Socket, partitions: 2
  ...
end
```

Thanks!

**Comment by chrismccord** [comment]
Also please track the progress of this issue and report back over on the phoenix side:
https://github.com/phoenixframework/phoenix/issues/2908

**Comment by niccolox** [comment]
I tried the "partitions: 2" on the same single core vm and it still errored

I upgraded the Linode node to a 2cpu core vm and error goes away on my chat example fork and also my original project

I NEVER would of found this one myself

# THANKS
