### ISSUE TITLE
Links to docs are out of date

### ISSUE THREAD

**Issue by riverrun** [chrismccord/phoenix_chat_example#9]
I know it's a bit pedantic, but:
in lib/chat/supervisor.ex (line 14), http://elixir-lang.org/docs/stable/Supervisor.Behaviour.html should be http://elixir-lang.org/docs/stable/elixir/Supervisor.html
and in lib/chat.ex (line 4), http://elixir-lang.org/docs/stable/Application.Behaviour.html should be http://elixir-lang.org/docs/stable/elixir/Application.html

**Comment by pedroassumpcao** [comment]
@riverrun I think this is already fixed in 0.8.0.
